refactor(husky): refactor husky pre-commit hooks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,15 +4,15 @@
 echo '🐱‍🏍✨ Testing your project before committing'
 
 # Check Prettier standards
-yarn check-format ||
+yarn format && yarn check-format ||
 (
     echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
-            Prettier Check Failed. Run npm run format, add changes and try commit again.';
+            Prettier Check Failed. Run yarn format, add changes and try commit again.';
     false;
 )
 
 # Check ESLint Standards
-yarn lint-staged && yarn check-lint ||
+yarn lint-staged && yarn check-lint && yarn lint ||
 (
         echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
@@ -30,13 +30,13 @@ yarn check-types ||
 # If everything passes... Now we can commit
 # echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
 
-# yarn build ||
-# (
-#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
-#             Next build failed: View the errors above to see why. 
-#     '
-#     false;
-# )
+yarn build ||
+(
+    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
+            Next build failed: View the errors above to see why. 
+    '
+    false;
+)
 
 # If everything passes... Now we can commit
 echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
